[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = --cov=setup_github_repo.app --cov-report=xml:packages/setup_github_repo/coverage/coverage.xml --cov-config=packages/setup_github_repo/.coveragerc
